Importing all necessary modules

In [126]:
try:
    import numpy as np
    # import pandas as pd
    # import matplotlib.pyplot as plt   
    import time
    import sys
    print("all modules imported succesfully")
except Exception as e:
    print(e)
    exit()

all modules imported succesfully


# Numpy Tutorial Code 

1D Array

In [127]:
oned_v_list = np.array([1,2,3])
oned_v_tuple = np.array((1,2,3))
oned_v_list,oned_v_tuple

(array([1, 2, 3]), array([1, 2, 3]))

2D Array

In [128]:
twod_v_list = np.array([[1,2,3],[4,5,6]])
twod_v_tuple = np.array(((1,2,3),(4,5,6)))
twod_v_list,twod_v_tuple

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

3D Array

In [129]:
threed_v_list = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
threed_v_tuple = np.array((((1,2,3),(4,5,6)),((7,8,9),(10,11,12))))
threed_v_list,threed_v_tuple

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]))

Array from List

In [130]:
list1 = [1,2,3]
np.array(list1)


array([1, 2, 3])

List from Array 

In [131]:
np.array(list1).tolist()


[1, 2, 3]

Array by Arange

In [132]:
np.arange(start=2,stop=10,step=3)


array([2, 5, 8])

Array of Zeros

In [133]:
np.zeros(shape=(2,3),dtype=int),np.zeros(shape=(2,3),dtype=bool)


(array([[0, 0, 0],
        [0, 0, 0]]),
 array([[False, False, False],
        [False, False, False]]))

Array of Ones

In [134]:
arr4 = np.ones(shape=(2,3),dtype=int)
arr4_b = np.ones(shape=(2,3),dtype=bool)
arr4,arr4_b

(array([[1, 1, 1],
        [1, 1, 1]]),
 array([[ True,  True,  True],
        [ True,  True,  True]]))

Linespace:- Array with even distribution

In [135]:
np.linspace(start=2,stop=10,num=5,endpoint=False)

array([2. , 3.6, 5.2, 6.8, 8.4])

In [136]:
np.linspace(start=2,stop=10,num=5,endpoint=True)

array([ 2.,  4.,  6.,  8., 10.])

In [137]:
np.linspace(start=2,stop=10,num=5,retstep=True)

(array([ 2.,  4.,  6.,  8., 10.]), 2.0)

Array with Random Numbers

In [138]:
ra1 = np.random.randint(0,10,15)
ra2 = np.random.randint(10,20,15)
ra3 = np.random.randint(20,30,15)

In [139]:
data = np.array([ra1,ra2,ra3])
data

array([[ 4,  3,  7,  6,  6,  6,  6,  4,  8,  9,  7,  4,  4,  0,  9],
       [12, 19, 16, 10, 17, 15, 16, 14, 16, 11, 13, 17, 16, 12, 16],
       [27, 25, 25, 23, 20, 21, 26, 24, 24, 28, 27, 27, 21, 29, 22]])

Array with ones on Diagnol and zeros elsewhere

In [140]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [141]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Same as above but ones are shifted by k times

In [142]:
np.eye(3,3,k=-2),np.eye(3,3,k=-1)

(array([[0., 0., 0.],
        [0., 0., 0.],
        [1., 0., 0.]]),
 array([[0., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.]]))

In [143]:
np.eye(3,3,k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [144]:
np.eye(3,3,k=1),np.eye(3,3,k=2)

(array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]]),
 array([[0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]))

Identity:- Same as eye but rows=columns

In [145]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

### Numpy Attributres

In [146]:
attr1 = np.array([5,6,7])
attr2 = np.array(((1,2,3),(4,5,6)))

For knowing dimension

In [147]:
attr1.ndim,attr2.ndim 

(1, 2)

For knowing size of each element in bytes

In [148]:
attr1.itemsize,attr2.itemsize

(4, 4)

For knowing length of array

In [149]:
attr1.size,attr2.size

(3, 6)

For knowing shape of array

In [150]:
attr1.shape,attr2.shape

((3,), (2, 3))

Numpy Array vs Python List

In [151]:
np.array((1,2.3,4)) ## get each element datatype converted to float

array([1. , 2.3, 4. ])

In [152]:
np.array((1,'hello',4)) ## get each element datatype converted to string

array(['1', 'hello', '4'], dtype='<U11')

Python list on additon gets merged but numpy arrays gets added

In [153]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [154]:
np.array([1,2,3])+np.array([4,5,6])

array([5, 7, 9])

Memory Comparison: Memory Consumption is very high of list on comparison with numpy array 

In [155]:
n=1000
python_list = range(n)
numpy_array = np.arange(n) 

In [156]:
print("Py list memory: ",sys.getsizeof(1)*len(python_list))
print("Np array memory: ",numpy_array.size*numpy_array.itemsize)

Py list memory:  28000
Np array memory:  4000


Speed Comparison: Speed of numpy array is very high on comparison with list

In [157]:
SIZE = 10_00_000

L1 = range(SIZE)
L2 = range(SIZE)

A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

In [158]:
start = time.time()
result = [(x+y) for x,y in zip(L1,L2)]
print((time.time()-start)*n)

95.09611129760742


In [159]:
start = time.time()
result = A1+A2
print((time.time()-start)*n)


16.9985294342041


### Reshaping Array

Normal Reshape

In [160]:
resh_arr  = np.arange(12)
resh_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [161]:
resh_arr_c = np.reshape(resh_arr,(4,3),order='C')
resh_arr_f = np.reshape(resh_arr,(4,3),order='F')
resh_arr_c,resh_arr_f

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]))

1D array to 3D array

In [162]:
one_d = np.arange(16)
one_d.ndim

1

In [163]:
threed = np.reshape(one_d,(2,2,4))
threed

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

2D to 3D array

In [168]:
twod = np.reshape(one_d,(4,4))
twod_to_threed = np.reshape(twod,(4,2,2))
twod_to_threed

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

2D to 1D

In [169]:
twod_to_oned = np.reshape(twod,16)
twod_to_oned

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])