Importing all necessary modules

In [1]:
try:
    import numpy as np
    # import pandas as pd
    # import matplotlib.pyplot as plt   
    import time
    import sys
    print("all modules imported succesfully")
except Exception as e:
    print(e)
    exit()

all modules imported succesfully


# Numpy Tutorial Code 

### Creation of array by diferent methods

1D Array

In [2]:
oned_v_list = np.array([1,2,3])
oned_v_tuple = np.array((1,2,3))
oned_v_list,oned_v_tuple

(array([1, 2, 3]), array([1, 2, 3]))

2D Array

In [3]:
twod_v_list = np.array([[1,2,3],[4,5,6]])
twod_v_tuple = np.array(((1,2,3),(4,5,6)))
twod_v_list,twod_v_tuple

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

3D Array

In [4]:
threed_v_list = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
threed_v_tuple = np.array((((1,2,3),(4,5,6)),((7,8,9),(10,11,12))))
threed_v_list,threed_v_tuple

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]))

Array from List

In [5]:
list1 = [1,2,3]
np.array(list1)


array([1, 2, 3])

List from Array 

In [6]:
np.array(list1).tolist()


[1, 2, 3]

Array by Arange

In [7]:
np.arange(start=2,stop=10,step=3)


array([2, 5, 8])

Array of Zeros

In [8]:
np.zeros(shape=(2,3),dtype=int),np.zeros(shape=(2,3),dtype=bool)


(array([[0, 0, 0],
        [0, 0, 0]]),
 array([[False, False, False],
        [False, False, False]]))

Array of Ones

In [9]:
arr4 = np.ones(shape=(2,3),dtype=int)
arr4_b = np.ones(shape=(2,3),dtype=bool)
arr4,arr4_b

(array([[1, 1, 1],
        [1, 1, 1]]),
 array([[ True,  True,  True],
        [ True,  True,  True]]))

Linespace:- Array with even distribution

In [10]:
np.linspace(start=2,stop=10,num=5,endpoint=False)

array([2. , 3.6, 5.2, 6.8, 8.4])

In [11]:
np.linspace(start=2,stop=10,num=5,endpoint=True)

array([ 2.,  4.,  6.,  8., 10.])

In [12]:
np.linspace(start=2,stop=10,num=5,retstep=True)

(array([ 2.,  4.,  6.,  8., 10.]), 2.0)

Array with Random Numbers

In [13]:
ra1 = np.random.randint(0,10,15)
ra2 = np.random.randint(10,20,15)
ra3 = np.random.randint(20,30,15)

In [14]:
data = np.array([ra1,ra2,ra3])
data

array([[ 3,  4,  4,  1,  8,  1,  1,  7,  5,  7,  3,  7,  0,  0,  8],
       [11, 12, 12, 13, 10, 14, 16, 14, 13, 17, 11, 19, 10, 13, 11],
       [29, 29, 20, 26, 24, 28, 23, 23, 22, 21, 24, 24, 22, 20, 24]])

Array with ones on Diagnol and zeros elsewhere

In [15]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [16]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Same as above but ones are shifted by k times

In [17]:
np.eye(3,3,k=-2),np.eye(3,3,k=-1)

(array([[0., 0., 0.],
        [0., 0., 0.],
        [1., 0., 0.]]),
 array([[0., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.]]))

In [18]:
np.eye(3,3,k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(3,3,k=1),np.eye(3,3,k=2)

(array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]]),
 array([[0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]))

Identity:- Same as eye but rows=columns

In [20]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

### Numpy Attributres

In [21]:
attr1 = np.array([5,6,7])
attr2 = np.array(((1,2,3),(4,5,6)))

For knowing dimension

In [22]:
attr1.ndim,attr2.ndim 

(1, 2)

For knowing size of each element in bytes

In [23]:
attr1.itemsize,attr2.itemsize

(4, 4)

For knowing length of array

In [24]:
attr1.size,attr2.size

(3, 6)

For knowing shape of array

In [25]:
attr1.shape,attr2.shape

((3,), (2, 3))

Numpy Array vs Python List

In [26]:
np.array((1,2.3,4)) ## get each element datatype converted to float

array([1. , 2.3, 4. ])

In [27]:
np.array((1,'hello',4)) ## get each element datatype converted to string

array(['1', 'hello', '4'], dtype='<U11')

Python list on additon gets merged but numpy arrays gets added

In [28]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [29]:
np.array([1,2,3])+np.array([4,5,6])

array([5, 7, 9])

Memory Comparison: Memory Consumption is very high of list on comparison with numpy array 

In [30]:
n=1000
python_list = range(n)
numpy_array = np.arange(n) 

In [31]:
print("Py list memory: ",sys.getsizeof(1)*len(python_list))
print("Np array memory: ",numpy_array.size*numpy_array.itemsize)

Py list memory:  28000
Np array memory:  4000


Speed Comparison: Speed of numpy array is very high on comparison with list

In [32]:
SIZE = 10_00_000

L1 = range(SIZE)
L2 = range(SIZE)

A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

In [33]:
start = time.time()
result = [(x+y) for x,y in zip(L1,L2)]
print((time.time()-start)*n)

118.99971961975098


In [34]:
start = time.time()
result = A1+A2
print((time.time()-start)*n)


16.794204711914062


### Reshaping Array

Normal Reshape

In [35]:
resh_arr  = np.arange(12)
resh_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
resh_arr_c = np.reshape(resh_arr,(4,3),order='C')
resh_arr_f = np.reshape(resh_arr,(4,3),order='F')
resh_arr_c,resh_arr_f

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]))

1D array to 3D array

In [37]:
one_d = np.arange(16)
one_d.ndim

1

In [38]:
threed = np.reshape(one_d,(2,2,4))
threed

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

2D to 3D array

In [39]:
twod = np.reshape(one_d,(4,4))
twod_to_threed = np.reshape(twod,(4,2,2))
twod_to_threed

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

2D to 1D

In [40]:
twod_to_oned = np.reshape(twod,16)
twod_to_oned

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

reshaping can be also done if you know atleast n-1 elements of shapes list

In [41]:
resh_m1_arr = np.arange(10)
resh_m1_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
resh_m1_arr.reshape((5,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
resh_m1_arr.reshape((2,-1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Resizing an array <br/>
2 Types <br/>
1. np.resize() 2. array.resize() <br/>
np.resize reapeats it initial elements till size is covered<br/>
but array.resize fills it with zero


BY NP.RESIZE

In [64]:
arr_to_be_resize_by_np = np.arange(10)
resized_arr_by_np = np.resize(arr_to_be_resize_by_np,(5,3))
resized_arr_by_np

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [9, 0, 1],
        [2, 3, 4]]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

BY ARRAY.RESIZE it is called in place operation because it changes size in the original array<br/>
so if you assign ARRAY.RESIZE to a new variable so the variable would not print<br/>
else it will resize original array

In [63]:
arr_to_be_resize_by_arr = np.arange(10)
arr_to_be_resize_by_arr.resize((5,3)) 
arr_to_be_resize_by_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [9, 0, 0],
       [0, 0, 0]])

### Aliasing and Cloning <br/>
Aliasing creates another refernce to same memory location<br/>
Cloning creates a copy and stores it in a differnent memory location


Aliasing Example

In [69]:
array_to_be_aliased = np.arange(10)
aliased_array = array_to_be_aliased[:]

In [71]:
array_to_be_aliased[0] = 9
array_to_be_aliased,aliased_array

(array([9, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([9, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

Cloning Example<br/>
Here on second line you can also use<br/>
np.copy(array_to_be_cloned)

In [72]:
array_to_be_cloned = np.arange(10)
cloned_array = array_to_be_cloned.copy() 
cloned_array_by_np = np.copy(array_to_be_cloned[:]) 


In [73]:
array_to_be_cloned[0] = 9
array_to_be_cloned,cloned_array

(array([9, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

### Base of an array when an array have the same memory location<br/> with the other array

In [74]:
non_base_array = np.arange(10)
base_array = non_base_array[:] 

base_array is using the same memory loaction of the non_base_array

In [75]:
non_base_array.base,base_array.base

(None, array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

But if we use copy the the will not use the same memory location

In [76]:
cloned_non_base_array = np.copy(non_base_array[:]) 

In [77]:
non_base_array.base,cloned_non_base_array.base

(None, None)

### view vs copy

view is same as aliasing but just writing view at the end

In [78]:
orig_arr_view = np.arange(10)
view_arr = orig_arr.view() 

In [80]:
view_arr[1] = 4
orig_arr_view.base,view_arr.base

(None, array([0, 4, 2, 3, 4, 5, 6, 7, 8, 9]))

In [82]:
orig_arr_view,view_arr

(array([0, 4, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 4, 2, 3, 4, 5, 6, 7, 8, 9]))

Copy is same as disscussed above

In [85]:
orig_arr_copy = np.arange(10)
copy_arr = np.copy(orig_arr_copy[:])
copy_arr[1] = 4
orig_arr_copy.base,copy_arr.base


(None, None)

In [86]:
orig_arr_copy,copy_arr


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 4, 2, 3, 4, 5, 6, 7, 8, 9]))

### Ravel vs Flatten vs Reshape(-1)<br/>
All make nth dimension array into 1D array<hr/>
Ravel is just 1d array and view of original_array<br/>
As well as reshape(-1) is same as ravel both create view<br/><br/>
Flatten is just 1d array and copy of original_array

Ravel Example

In [89]:
n_dim_array_ravel = np.arange(6).reshape((3,-1))
ravel_array = n_dim_array_ravel.ravel()
ravel_array[2] = 9
ravel_array,n_dim_array_ravel

(array([0, 1, 9, 3, 4, 5]),
 array([[0, 1],
        [9, 3],
        [4, 5]]))

Flatten Example

In [90]:
n_dim_array_flatten = np.arange(6).reshape((3,-1))
flatten_array = n_dim_array_flatten.flatten()
flatten_array[2] = 9
flatten_array,n_dim_array_flatten


(array([0, 1, 9, 3, 4, 5]),
 array([[0, 1],
        [2, 3],
        [4, 5]]))

Reshape(-1) Example 

In [91]:
n_dim_array_reshape = np.arange(6).reshape((3,-1))
reshape_array = n_dim_array_reshape.reshape(-1)
reshape_array[2] = 9
reshape_array,n_dim_array_reshape

(array([0, 1, 9, 3, 4, 5]),
 array([[0, 1],
        [9, 3],
        [4, 5]]))

### Copy vs Deepcopy<br/>
copy me agar array element list tuple etc type ka hua to vo modificaton dono jagah reflect karega<br/>
magar deepcopy me modificaton reflect nahi karega

In [106]:
arr_to_be_copy = np.array([10,20,30,[40,50]],dtype=object)
arr_to_be_deep_copy = np.array([10,20,30,[40,50]],dtype=object)


Simple Copy Example

In [107]:
copy_of_arr = arr_to_be_copy.copy()
copy_of_arr[3][0] = 60
copy_of_arr,arr_to_be_copy

(array([10, 20, 30, list([60, 50])], dtype=object),
 array([10, 20, 30, list([60, 50])], dtype=object))

Deepcopy Example

In [109]:
import copy
copy_of_deep_arr = copy.deepcopy(arr_to_be_deep_copy)
copy_of_deep_arr[3][0] = 60
copy_of_deep_arr,arr_to_be_deep_copy

(array([10, 20, 30, list([60, 50])], dtype=object),
 array([10, 20, 30, list([40, 50])], dtype=object))

### SUM PRODUCT SORT OF ARRAY<br/>ALL THESE FUNCS CAN BE INVOKED BY<BR/>
np.sum(),np.prod(),np.sort()

### SUM of ARRAY<br/>
Axis 0 for Column and 1 for Row

In [114]:
sum_arr = np.array([1,2,3,4])
sum_arr.sum()

10

In [124]:
sum_arr=sum_arr.reshape(2,-1)
sum_arr.sum(axis=0),sum_arr.sum(axis=1)

(array([4, 6]), array([3, 7]))

### Product of ARRAY<br/>
Axis 0 for Column and 1 for Row


In [127]:
prod_arr = np.arange(1,5)
prod_arr.prod()

24

In [129]:
prod_arr = prod_arr.reshape(2,-1)
prod_arr.prod(axis=0),prod_arr.prod(axis=1)

(array([3, 8]), array([ 2, 12]))

### Sorting ARRAY<br/>
Axis 0 for Column and 1 for Row

In [135]:
sort_arr = np.array([4,3,2,1])
sort_arr.sort()
sort_arr

array([1, 2, 3, 4])

In [140]:
sort_arr_axis = np.array([[4,3],[2,1]])
sort_arr_axis.sort(axis=0)
sort_arr_axis 

array([[2, 1],
       [4, 3]])

In [141]:
sort_arr_axis.sort(axis=1)
sort_arr_axis

array([[1, 2],
       [3, 4]])

Axis 0 for Column and 1 for row

In [144]:
np.sum(sum_arr,axis=0),np.sum(sum_arr,axis=1)

(array([4, 6]), array([3, 7]))

### ARRAY STACKING

In [152]:
array_to_be_stacked1 = np.arange(1,4)
array_to_be_stacked2 = np.arange(4,7)
stacked_array1 = np.vstack((array_to_be_stacked1,array_to_be_stacked2))
stacked_array1

array([[1, 2, 3],
       [4, 5, 6]])

In [163]:
array_to_be_stacked3 = np.arange(7,10)
stacked_array2 = np.vstack((array_to_be_stacked3,stacked_array1))
stacked_array2

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

Stacking for 2D array

In [180]:
twod_arr_to_be_stacked1 = np.eye(3,3,dtype=int)
twod_arr_to_be_stacked2 = np.eye(3,3,k=-2,dtype=int)
np.vstack((twod_arr_to_be_stacked1,twod_arr_to_be_stacked2))


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0]])