Importing all necessary modules

In [30]:
try:
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    print("all modules imported succesfully")
except Exception as e:
    print(e)
    exit()

all modules imported succesfully


Numpy Tutorial Code 

1D Array

In [31]:
oned_v_list = np.array([1,2,3])
oned_v_tuple = np.array((1,2,3))
oned_v_list,oned_v_tuple

(array([1, 2, 3]), array([1, 2, 3]))

2D Array

In [32]:
twod_v_list = np.array([[1,2,3],[4,5,6]])
twod_v_tuple = np.array(((1,2,3),(4,5,6)))
twod_v_list,twod_v_tuple

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

3D Array

In [33]:
threed_v_list = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
threed_v_tuple = np.array((((1,2,3),(4,5,6)),((7,8,9),(10,11,12))))
threed_v_list,threed_v_tuple

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]))

Array from List

In [49]:
list1 = [1,2,3]
np.array(list1)


array([1, 2, 3])

List from Array 

In [50]:
np.array(list1).tolist()


[1, 2, 3]

Array by Arange

In [48]:
np.arange(start=2,stop=10,step=3)


array([2, 5, 8])

Array of Zeros

In [47]:
np.zeros(shape=(2,3),dtype=int),np.zeros(shape=(2,3),dtype=bool)


(array([[0, 0, 0],
        [0, 0, 0]]),
 array([[False, False, False],
        [False, False, False]]))

Array of Ones

In [45]:
arr4 = np.ones(shape=(2,3),dtype=int)
arr4_b = np.ones(shape=(2,3),dtype=bool)
arr4,arr4_b

(array([[1, 1, 1],
        [1, 1, 1]]),
 array([[ True,  True,  True],
        [ True,  True,  True]]))

Linespace:- Array with even distribution

In [55]:
np.linspace(start=2,stop=10,num=5,endpoint=False)

array([2. , 3.6, 5.2, 6.8, 8.4])

In [54]:
np.linspace(start=2,stop=10,num=5,endpoint=True)

array([ 2.,  4.,  6.,  8., 10.])

In [56]:
np.linspace(start=2,stop=10,num=5,retstep=True)

(array([ 2.,  4.,  6.,  8., 10.]), 2.0)

Array with Random Numbers

In [58]:
ra1 = np.random.randint(0,10,15)
ra2 = np.random.randint(10,20,15)
ra3 = np.random.randint(20,30,15)

In [60]:
data = np.array([ra1,ra2,ra3])
data

array([[ 4,  3,  3,  3,  1,  0,  4,  0,  9,  8,  8,  2,  3,  0,  0],
       [19, 10, 11, 12, 14, 19, 13, 13, 15, 18, 12, 13, 19, 10, 15],
       [21, 28, 28, 27, 24, 26, 29, 26, 24, 26, 23, 22, 21, 29, 28]])

Array with ones on Diagnol and zeros elsewhere

In [61]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [66]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

Same as above but ones are shifted by k times

In [72]:
np.eye(3,3,k=-2),np.eye(3,3,k=-1)

(array([[0., 0., 0.],
        [0., 0., 0.],
        [1., 0., 0.]]),
 array([[0., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.]]))

In [73]:
np.eye(3,3,k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.eye(3,3,k=1),np.eye(3,3,k=2)

(array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]]),
 array([[0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]))

Identity:- Same as eye but rows=columns

In [77]:
np.identity(2)

(array([[1., 0.],
        [0., 1.]]),
 array([[1., 0.],
        [0., 1.]]))