Importing all necessary modules

In [231]:
try:
    import numpy as np
    import pandas as pd
    # import matplotlib.pyplot as plt   
    import time
    import sys
    print("all modules imported succesfully")
except Exception as e:
    print(e)
    exit()

all modules imported succesfully


# Numpy Tutorial Code 

### Creation of array by diferent methods

1D Array

In [232]:
oned_v_list = np.array([1,2,3])
oned_v_tuple = np.array((1,2,3))
oned_v_list,oned_v_tuple

(array([1, 2, 3]), array([1, 2, 3]))

2D Array

In [233]:
twod_v_list = np.array([[1,2,3],[4,5,6]])
twod_v_tuple = np.array(((1,2,3),(4,5,6)))
twod_v_list,twod_v_tuple

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

3D Array

In [234]:
threed_v_list = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
threed_v_tuple = np.array((((1,2,3),(4,5,6)),((7,8,9),(10,11,12))))
threed_v_list,threed_v_tuple

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]))

Array from List

In [235]:
list1 = [1,2,3]
np.array(list1)


array([1, 2, 3])

List from Array 

In [236]:
np.array(list1).tolist()


[1, 2, 3]

Array by Arange

In [237]:
np.arange(start=2,stop=10,step=3)


array([2, 5, 8])

Array of Zeros

In [238]:
np.zeros(shape=(2,3),dtype=int),np.zeros(shape=(2,3),dtype=bool)


(array([[0, 0, 0],
        [0, 0, 0]]),
 array([[False, False, False],
        [False, False, False]]))

Array of Ones

In [239]:
arr4 = np.ones(shape=(2,3),dtype=int)
arr4_b = np.ones(shape=(2,3),dtype=bool)
arr4,arr4_b

(array([[1, 1, 1],
        [1, 1, 1]]),
 array([[ True,  True,  True],
        [ True,  True,  True]]))

Linespace:- Array with even distribution

In [240]:
np.linspace(start=2,stop=10,num=5,endpoint=False)

array([2. , 3.6, 5.2, 6.8, 8.4])

In [241]:
np.linspace(start=2,stop=10,num=5,endpoint=True)

array([ 2.,  4.,  6.,  8., 10.])

In [242]:
np.linspace(start=2,stop=10,num=5,retstep=True)

(array([ 2.,  4.,  6.,  8., 10.]), 2.0)

Array with Random Numbers

In [243]:
ra1 = np.random.randint(0,10,15)
ra2 = np.random.randint(10,20,15)
ra3 = np.random.randint(20,30,15)

In [244]:
data = np.array([ra1,ra2,ra3])
data

array([[ 7,  3,  8,  0,  9,  0,  1,  3,  8,  2,  8,  3,  5,  8,  9],
       [13, 12, 11, 15, 18, 19, 19, 16, 12, 15, 16, 15, 13, 12, 12],
       [29, 21, 29, 21, 23, 24, 28, 27, 20, 24, 22, 21, 26, 23, 27]])

Array with ones on Diagnol and zeros elsewhere

In [245]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [246]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Same as above but ones are shifted by k times

In [247]:
np.eye(3,3,k=-2),np.eye(3,3,k=-1)

(array([[0., 0., 0.],
        [0., 0., 0.],
        [1., 0., 0.]]),
 array([[0., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.]]))

In [248]:
np.eye(3,3,k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [249]:
np.eye(3,3,k=1),np.eye(3,3,k=2)

(array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]]),
 array([[0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]))

Identity:- Same as eye but rows=columns

In [250]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

### Numpy Attributres

In [251]:
attr1 = np.array([5,6,7])
attr2 = np.array(((1,2,3),(4,5,6)))

For knowing dimension

In [252]:
attr1.ndim,attr2.ndim 

(1, 2)

For knowing size of each element in bytes

In [253]:
attr1.itemsize,attr2.itemsize

(4, 4)

For knowing length of array

In [254]:
attr1.size,attr2.size

(3, 6)

For knowing shape of array

In [255]:
attr1.shape,attr2.shape

((3,), (2, 3))

Numpy Array vs Python List

In [256]:
np.array((1,2.3,4)) ## get each element datatype converted to float

array([1. , 2.3, 4. ])

In [257]:
np.array((1,'hello',4)) ## get each element datatype converted to string

array(['1', 'hello', '4'], dtype='<U11')

Python list on additon gets merged but numpy arrays gets added

In [258]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [259]:
np.array([1,2,3])+np.array([4,5,6])

array([5, 7, 9])

Memory Comparison: Memory Consumption is very high of list on comparison with numpy array 

In [260]:
n=1000
python_list = range(n)
numpy_array = np.arange(n) 

In [261]:
print("Py list memory: ",sys.getsizeof(1)*len(python_list))
print("Np array memory: ",numpy_array.size*numpy_array.itemsize)

Py list memory:  28000
Np array memory:  4000


Speed Comparison: Speed of numpy array is very high on comparison with list

In [262]:
SIZE = 10_00_000

L1 = range(SIZE)
L2 = range(SIZE)

A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

In [263]:
start = time.time()
result = [(x+y) for x,y in zip(L1,L2)]
print((time.time()-start)*n)

91.88961982727051


In [264]:
start = time.time()
result = A1+A2
print((time.time()-start)*n)


11.913537979125977


### Reshaping Array

Normal Reshape

In [265]:
resh_arr  = np.arange(12)
resh_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [266]:
resh_arr_c = np.reshape(resh_arr,(4,3),order='C')
resh_arr_f = np.reshape(resh_arr,(4,3),order='F')
resh_arr_c,resh_arr_f

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]))

1D array to 3D array

In [267]:
one_d = np.arange(16)
one_d.ndim

1

In [268]:
threed = np.reshape(one_d,(2,2,4))
threed

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

2D to 3D array

In [269]:
twod = np.reshape(one_d,(4,4))
twod_to_threed = np.reshape(twod,(4,2,2))
twod_to_threed

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

2D to 1D

In [270]:
twod_to_oned = np.reshape(twod,16)
twod_to_oned

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

reshaping can be also done if you know atleast n-1 elements of shapes list

In [271]:
resh_m1_arr = np.arange(10)
resh_m1_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [272]:
resh_m1_arr.reshape((5,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [273]:
resh_m1_arr.reshape((2,-1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Resizing an array <br/>
2 Types <br/>
1. np.resize() 2. array.resize() <br/>
np.resize reapeats it initial elements till size is covered<br/>
but array.resize fills it with zero


BY NP.RESIZE

In [274]:
arr_to_be_resize_by_np = np.arange(10)
resized_arr_by_np = np.resize(arr_to_be_resize_by_np,(5,3))
resized_arr_by_np

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [9, 0, 1],
       [2, 3, 4]])

BY ARRAY.RESIZE it is called in place operation because it changes size in the original array<br/>
so if you assign ARRAY.RESIZE to a new variable so the variable would not print<br/>
else it will resize original array

In [275]:
arr_to_be_resize_by_arr = np.arange(10)
arr_to_be_resize_by_arr.resize((5,3)) 
arr_to_be_resize_by_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [9, 0, 0],
       [0, 0, 0]])

### Aliasing and Cloning <br/>
Aliasing creates another refernce to same memory location<br/>
Cloning creates a copy and stores it in a differnent memory location


Aliasing Example

In [276]:
array_to_be_aliased = np.arange(10)
aliased_array = array_to_be_aliased[:]

In [277]:
array_to_be_aliased[0] = 9
array_to_be_aliased,aliased_array

(array([9, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([9, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

Cloning Example<br/>
Here on second line you can also use<br/>
np.copy(array_to_be_cloned)

In [278]:
array_to_be_cloned = np.arange(10)
cloned_array = array_to_be_cloned.copy() 
cloned_array_by_np = np.copy(array_to_be_cloned[:]) 


In [279]:
array_to_be_cloned[0] = 9
array_to_be_cloned,cloned_array

(array([9, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

### Base of an array when an array have the same memory location<br/> with the other array

In [280]:
non_base_array = np.arange(10)
base_array = non_base_array[:] 

base_array is using the same memory loaction of the non_base_array

In [281]:
non_base_array.base,base_array.base

(None, array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

But if we use copy the the will not use the same memory location

In [282]:
cloned_non_base_array = np.copy(non_base_array[:]) 

In [283]:
non_base_array.base,cloned_non_base_array.base

(None, None)

### view vs copy

view is same as aliasing but just writing view at the end

In [284]:
orig_arr_view = np.arange(10)
view_arr = orig_arr_view.view() 

In [285]:
view_arr[1] = 4
orig_arr_view.base,view_arr.base

(None, array([0, 4, 2, 3, 4, 5, 6, 7, 8, 9]))

In [286]:
orig_arr_view,view_arr

(array([0, 4, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 4, 2, 3, 4, 5, 6, 7, 8, 9]))

Copy is same as disscussed above

In [287]:
orig_arr_copy = np.arange(10)
copy_arr = np.copy(orig_arr_copy[:])
copy_arr[1] = 4
orig_arr_copy.base,copy_arr.base


(None, None)

In [288]:
orig_arr_copy,copy_arr


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 4, 2, 3, 4, 5, 6, 7, 8, 9]))

### Ravel vs Flatten vs Reshape(-1)<br/>
All make nth dimension array into 1D array<hr/>
Ravel is just 1d array and view of original_array<br/>
As well as reshape(-1) is same as ravel both create view<br/><br/>
Flatten is just 1d array and copy of original_array

Ravel Example

In [289]:
n_dim_array_ravel = np.arange(6).reshape((3,-1))
ravel_array = n_dim_array_ravel.ravel()
ravel_array[2] = 9
ravel_array,n_dim_array_ravel

(array([0, 1, 9, 3, 4, 5]),
 array([[0, 1],
        [9, 3],
        [4, 5]]))

Flatten Example

In [290]:
n_dim_array_flatten = np.arange(6).reshape((3,-1))
flatten_array = n_dim_array_flatten.flatten()
flatten_array[2] = 9
flatten_array,n_dim_array_flatten


(array([0, 1, 9, 3, 4, 5]),
 array([[0, 1],
        [2, 3],
        [4, 5]]))

Reshape(-1) Example 

In [291]:
n_dim_array_reshape = np.arange(6).reshape((3,-1))
reshape_array = n_dim_array_reshape.reshape(-1)
reshape_array[2] = 9
reshape_array,n_dim_array_reshape

(array([0, 1, 9, 3, 4, 5]),
 array([[0, 1],
        [9, 3],
        [4, 5]]))

### Copy vs Deepcopy<br/>
copy me agar array element list tuple etc type ka hua to vo modificaton dono jagah reflect karega<br/>
magar deepcopy me modificaton reflect nahi karega

In [292]:
arr_to_be_copy = np.array([10,20,30,[40,50]],dtype=object)
arr_to_be_deep_copy = np.array([10,20,30,[40,50]],dtype=object)


Simple Copy Example

In [293]:
copy_of_arr = arr_to_be_copy.copy()
copy_of_arr[3][0] = 60
copy_of_arr,arr_to_be_copy

(array([10, 20, 30, list([60, 50])], dtype=object),
 array([10, 20, 30, list([60, 50])], dtype=object))

Deepcopy Example

In [294]:
import copy
copy_of_deep_arr = copy.deepcopy(arr_to_be_deep_copy)
copy_of_deep_arr[3][0] = 60
copy_of_deep_arr,arr_to_be_deep_copy

(array([10, 20, 30, list([60, 50])], dtype=object),
 array([10, 20, 30, list([40, 50])], dtype=object))

### SUM PRODUCT SORT OF ARRAY<br/>ALL THESE FUNCS CAN BE INVOKED BY<BR/>
np.sum(),np.prod(),np.sort()

### SUM of ARRAY<br/>
Axis 0 for Column and 1 for Row

In [295]:
sum_arr = np.array([1,2,3,4])
sum_arr.sum()

10

In [296]:
sum_arr=sum_arr.reshape(2,-1)
sum_arr.sum(axis=0),sum_arr.sum(axis=1)

(array([4, 6]), array([3, 7]))

### Product of ARRAY<br/>
Axis 0 for Column and 1 for Row


In [297]:
prod_arr = np.arange(1,5)
prod_arr.prod()

24

In [298]:
prod_arr = prod_arr.reshape(2,-1)
prod_arr.prod(axis=0),prod_arr.prod(axis=1)

(array([3, 8]), array([ 2, 12]))

### Sorting ARRAY<br/>
Axis 0 for Column and 1 for Row

In [299]:
sort_arr = np.array([4,3,2,1])
sort_arr.sort()
sort_arr

array([1, 2, 3, 4])

In [300]:
sort_arr_axis = np.array([[4,3],[2,1]])
sort_arr_axis.sort(axis=0)
sort_arr_axis 

array([[2, 1],
       [4, 3]])

In [301]:
sort_arr_axis.sort(axis=1)
sort_arr_axis

array([[1, 2],
       [3, 4]])

Axis 0 for Column and 1 for row

In [302]:
np.sum(sum_arr,axis=0),np.sum(sum_arr,axis=1)

(array([4, 6]), array([3, 7]))

### ARRAY STACKING

Vertical Stacking

In [303]:
array_to_be_stacked1 = np.arange(1,4)
array_to_be_stacked2 = np.arange(4,7)
stacked_array1 = np.vstack((array_to_be_stacked1,array_to_be_stacked2))
stacked_array1

array([[1, 2, 3],
       [4, 5, 6]])

In [304]:
array_to_be_stacked3 = np.arange(7,10)
stacked_array2 = np.vstack((array_to_be_stacked3,stacked_array1))
stacked_array2

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

Stacking for 2D array

In [305]:
twod_arr_to_be_stacked1 = np.eye(3,3,dtype=int)
twod_arr_to_be_stacked2 = np.eye(3,3,k=-2,dtype=int)
np.vstack((twod_arr_to_be_stacked1,twod_arr_to_be_stacked2))


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0]])

Horizontal Stacking

In [306]:
h_arr_to_be_staked1 = np.arange(1,4)
h_arr_to_be_staked2 = np.arange(4,7)
np.hstack((h_arr_to_be_staked1,h_arr_to_be_staked2))

array([1, 2, 3, 4, 5, 6])

In [307]:
h_arr_to_be_staked3 = np.array([[1,2,3],[4,5,6]])
h_arr_to_be_staked4 = np.array([[7,8,9],[10,11,12]])
np.hstack((h_arr_to_be_staked3,h_arr_to_be_staked4))



array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### Splitting an array<br/>
divides an array into n equal parts

In [308]:
array_to_split = np.arange(1,11)
np.split(array_to_split,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [309]:
np.split(array_to_split,[3])

[array([1, 2, 3]), array([ 4,  5,  6,  7,  8,  9, 10])]

In [310]:
np.split(array_to_split,[3,6])


[array([1, 2, 3]), array([4, 5, 6]), array([ 7,  8,  9, 10])]

Split 2D Array

In [311]:
twod_arr_to_split = np.arange(1,17).reshape(4,-1)
twod_arr_to_split

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [312]:
np.split(twod_arr_to_split,2,axis=0)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [313]:
np.split(twod_arr_to_split,[3],axis=0)


[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [314]:
vertically_split_arr = np.split(twod_arr_to_split,[3],axis=1)
vertically_split_arr[0]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [315]:
vertically_split_arr[1]

array([[ 4],
       [ 8],
       [12],
       [16]])

### Arthematic function on Array

In [316]:
art_arr1 = np.arange(1,4)
art_arr2 = np.arange(4,7)

In [317]:
np.add(art_arr1,art_arr2)

array([5, 7, 9])

In [318]:
np.subtract(art_arr1,art_arr2)


array([-3, -3, -3])

In [319]:
np.multiply(art_arr1,art_arr2)


array([ 4, 10, 18])

In [320]:
np.divide(art_arr1,art_arr2)


array([0.25, 0.4 , 0.5 ])

In [321]:
np.mod(art_arr1,art_arr2)


array([1, 2, 3])

In [322]:
np.power(art_arr1,art_arr2)

array([  1,  32, 729])

In [323]:
np.add(art_arr1,art_arr2)

array([5, 7, 9])

In [324]:
twod_art_arr1 = np.arange(0,9).reshape(3,-1)
twod_art_arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [325]:
np.max(twod_art_arr1)

8

In [326]:
np.min(twod_art_arr1)


0

In [327]:
np.std(twod_art_arr1)


2.581988897471611

In [328]:
np.sqrt(twod_art_arr1)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

### Array Slicing<br/>
arr[start:stop:step] 

Slicing 1D array

In [329]:
slicing_arr1 = np.arange(11,22)
slicing_arr1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [330]:
slicing_arr[1:4]

array([12, 13, 14])

In [331]:
slicing_arr2 = np.arange(100,210,10)
slicing_arr2

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200])

In [332]:
slicing_arr2[1:3]

array([110, 120])

In [333]:
slicing_arr1[5:]

array([16, 17, 18, 19, 20, 21])

In [334]:
slicing_arr1[:4]

array([11, 12, 13, 14])

In [335]:
slicing_arr1[:8]

array([11, 12, 13, 14, 15, 16, 17, 18])

In [336]:
slicing_arr1[:5][::-1],slicing_arr1[-4:-1]

(array([15, 14, 13, 12, 11]), array([18, 19, 20]))

In [337]:
slicing_arr1[-1:-5:-1][::-1],slicing_arr1[-4:]

(array([18, 19, 20, 21]), array([18, 19, 20, 21]))

In [338]:
slicing_arr1[::2]

array([11, 13, 15, 17, 19, 21])

Slicing 2D Array

In [339]:
twod_arr_sliced = np.arange(9).reshape(3,-1)
twod_arr_sliced[1:,0:]+=1
twod_arr_sliced

array([[0, 1, 2],
       [4, 5, 6],
       [7, 8, 9]])

In [340]:
twod_arr_sliced[0][0]

0

In [341]:
twod_arr_sliced[-1][-2]


8

In [342]:
twod_arr_sliced[1:,1:]

array([[5, 6],
       [8, 9]])

In [343]:
twod_arr_sliced[1:2,2],twod_arr_sliced[1][2],twod_arr_sliced[-2][-1]

(array([6]), 6, 6)

In [344]:
twod_arr_sliced[-1]

array([7, 8, 9])

In [345]:
twod_arr_sliced[-2]

array([4, 5, 6])

### Broadcasting

In [346]:
br_arr1 = np.arange(1,4)
br_arr2 = np.arange(4,7)

In [347]:
br_arr1+br_arr2

array([5, 7, 9])

In [348]:
scalar_value = 4
br_arr1+scalar_value

array([5, 6, 7])

Broadcasting of two array with diff dimension

In [349]:
arr_dim1 = np.arange(1,5).reshape(2,-1)
arr_dim2 = np.array([1,2])
arr_dim1+arr_dim2,arr_dim1


(array([[2, 4],
        [4, 6]]),
 array([[1, 2],
        [3, 4]]))

BroadCasting will give error if shape does'nt match

In [350]:
arr_sh1 = np.arange(1,4)
arr_sh2 = np.arange(1,5)
## arr_sh1+arr_sh2 ## this will give error

### Convert Pandas Dataframe to a Numpy Array

In [351]:
data = pd.read_csv('data.csv')
data.head(),type(data)

(   Duration  Pulse  Maxpulse  Calories
 0        60    110       130     409.1
 1        60    117       145     479.0
 2        60    103       135     340.0
 3        45    109       175     282.4
 4        45    117       148     406.0,
 pandas.core.frame.DataFrame)

Converting dataframe to array

In [352]:
data_numpy = data.values
#### or Both are Same #######
data_numpy = data.to_numpy  #### widely used

In [353]:
data_numpy[:5,],data_numpy.shape,data_numpy.dtype

TypeError: 'method' object is not subscriptable

In [ ]:
data.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

Converting only 1 column to array

In [ ]:
data1 = data['Duration'].values
data1

array([ 60,  60,  60,  45,  45,  60,  60,  45,  30,  60,  60,  60,  60,
        60,  60,  60,  60,  45,  60,  45,  60,  45,  60,  45,  60,  60,
        60,  60,  60,  60,  60,  45,  60,  60,  60,  60,  60,  60,  60,
        45,  45,  60,  60,  60,  60,  60,  60,  45,  45,  60,  60,  80,
        60,  60,  30,  60,  60,  45,  20,  45, 210, 160, 160,  45,  20,
       180, 150, 150,  20, 300, 150,  60,  90, 150,  45,  90,  45,  45,
       120, 270,  30,  45,  30, 120,  45,  30,  45, 120,  45,  20, 180,
        45,  30,  15,  20,  20,  30,  25,  30,  90,  20,  90,  90,  90,
        30,  30, 180,  30,  90, 210,  60,  45,  15,  45,  60,  60,  60,
        60,  60,  60,  30,  45,  60,  60,  60,  60,  60,  60,  90,  60,
        60,  60,  60,  60,  60,  20,  45,  45,  45,  20,  60,  60,  45,
        45,  60,  45,  60,  60,  30,  60,  60,  60,  60,  30,  60,  60,
        60,  60,  60,  30,  30,  45,  45,  45,  60,  60,  60,  75,  75],
      dtype=int64)

In [ ]:
type(data1)

numpy.ndarray

### Concatenation/Joining of arrays<br/>
isme axis ulta chalta hai<br/>
axis 0 row aur 1 column ke liye 

In [ ]:
join_arr1 = np.arange(1,4)
join_arr2 = np.arange(4,7)
np.concatenate((join_arr1,join_arr2)) 

array([1, 2, 3, 4, 5, 6])

In [ ]:
join_arr3 = np.arange(1,5).reshape(2,-1)
join_arr4 = np.arange(5,9).reshape(2,-1)

In [ ]:
np.concatenate((join_arr3,join_arr4),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.concatenate((join_arr3,join_arr4),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.concatenate((join_arr3,join_arr4),axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8])