Importing all necessary modules

In [52]:
try:
    import numpy as np
    # import pandas as pd
    # import matplotlib.pyplot as plt   
    import time
    import sys
    print("all modules imported succesfully")
except Exception as e:
    print(e)
    exit()

all modules imported succesfully


Numpy Tutorial Code 

1D Array

In [2]:
oned_v_list = np.array([1,2,3])
oned_v_tuple = np.array((1,2,3))
oned_v_list,oned_v_tuple

(array([1, 2, 3]), array([1, 2, 3]))

2D Array

In [3]:
twod_v_list = np.array([[1,2,3],[4,5,6]])
twod_v_tuple = np.array(((1,2,3),(4,5,6)))
twod_v_list,twod_v_tuple

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

3D Array

In [4]:
threed_v_list = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
threed_v_tuple = np.array((((1,2,3),(4,5,6)),((7,8,9),(10,11,12))))
threed_v_list,threed_v_tuple

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]))

Array from List

In [5]:
list1 = [1,2,3]
np.array(list1)


array([1, 2, 3])

List from Array 

In [6]:
np.array(list1).tolist()


[1, 2, 3]

Array by Arange

In [7]:
np.arange(start=2,stop=10,step=3)


array([2, 5, 8])

Array of Zeros

In [8]:
np.zeros(shape=(2,3),dtype=int),np.zeros(shape=(2,3),dtype=bool)


(array([[0, 0, 0],
        [0, 0, 0]]),
 array([[False, False, False],
        [False, False, False]]))

Array of Ones

In [9]:
arr4 = np.ones(shape=(2,3),dtype=int)
arr4_b = np.ones(shape=(2,3),dtype=bool)
arr4,arr4_b

(array([[1, 1, 1],
        [1, 1, 1]]),
 array([[ True,  True,  True],
        [ True,  True,  True]]))

Linespace:- Array with even distribution

In [10]:
np.linspace(start=2,stop=10,num=5,endpoint=False)

array([2. , 3.6, 5.2, 6.8, 8.4])

In [11]:
np.linspace(start=2,stop=10,num=5,endpoint=True)

array([ 2.,  4.,  6.,  8., 10.])

In [12]:
np.linspace(start=2,stop=10,num=5,retstep=True)

(array([ 2.,  4.,  6.,  8., 10.]), 2.0)

Array with Random Numbers

In [13]:
ra1 = np.random.randint(0,10,15)
ra2 = np.random.randint(10,20,15)
ra3 = np.random.randint(20,30,15)

In [14]:
data = np.array([ra1,ra2,ra3])
data

array([[ 8,  7,  7,  9,  1,  8,  8,  8,  6,  2,  8,  9,  4,  6,  0],
       [17, 13, 13, 16, 17, 15, 17, 12, 10, 15, 17, 18, 16, 10, 19],
       [22, 21, 22, 23, 23, 28, 22, 29, 24, 20, 25, 22, 24, 22, 22]])

Array with ones on Diagnol and zeros elsewhere

In [15]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [16]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Same as above but ones are shifted by k times

In [17]:
np.eye(3,3,k=-2),np.eye(3,3,k=-1)

(array([[0., 0., 0.],
        [0., 0., 0.],
        [1., 0., 0.]]),
 array([[0., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.]]))

In [18]:
np.eye(3,3,k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(3,3,k=1),np.eye(3,3,k=2)

(array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]]),
 array([[0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]))

Identity:- Same as eye but rows=columns

In [20]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

Numpy Attributres

In [28]:
attr1 = np.array([5,6,7])
attr2 = np.array(((1,2,3),(4,5,6)))

For knowing dimension

In [30]:
attr1.ndim,attr2.ndim 

(1, 2)

For knowing size of each element in bytes

In [31]:
attr1.itemsize,attr2.itemsize

(4, 4)

For knowing length of array

In [32]:
attr1.size,attr2.size

(3, 6)

For knowing shape of array

In [33]:
attr1.shape,attr2.shape

((3,), (2, 3))

Numpy Array vs Python List

In [36]:
np.array((1,2.3,4)) ## get each element datatype converted to float

array([1. , 2.3, 4. ])

In [35]:
np.array((1,'hello',4)) ## get each element datatype converted to string

array(['1', 'hello', '4'], dtype='<U11')

Python list on additon gets merged but numpy arrays gets added

In [41]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [42]:
np.array([1,2,3])+np.array([4,5,6])

array([5, 7, 9])

Memory Comparison: Memory Consumption is very high of list on comparison with numpy array 

In [44]:
n=1000
python_list = range(n)
numpy_array = np.arange(n) 

In [51]:
print("Py list memory: ",sys.getsizeof(1)*len(python_list))
print("Np array memory: ",numpy_array.size*numpy_array.itemsize)

Py list memory:  28000
Np array memory:  4000


Speed Comparison: Speed of numpy array is very high on comparison with list

In [53]:
SIZE = 10_00_000

L1 = range(SIZE)
L2 = range(SIZE)

A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

In [100]:
start = time.time()
result = [(x+y) for x,y in zip(L1,L2)]
print((time.time()-start)*n)

99.0602970123291


In [112]:
start = time.time()
result = A1+A2
print((time.time()-start)*n)


1.9984245300292969
